# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20160113_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Book Title'),
        ),
    ]
